### PR TITLE
continue with react-native-community/art

### PR DESCRIPTION
**Pull request by Preeternal**
Description is in issue https://github.com/nihgwu/react-native-pie/issues/22

### CODE REVIEW

**Comment by Preeternal** [comment]
@nihgwu Could you please to review? Tested with new changes community Art. Works as expected both Android and iOS.

**Comment by zgordon01** [comment]
I'll test this when I get time but the changes look good

**Comment by zgordon01** [comment]
@Preeternal If you could, we should bump the version to `1.1`.
I'm about to double check things, but assuming everything is all good and the version is bumped, I will get this merged

**Review by zgordon01 — APPROVED** [review]

**Comment by nihgwu** [comment]
Thanks @zgordon01 , I'll add you as the admin of the package so you can publish versions too

**Comment by milindagrawal** [comment]
@nihgwu  Can you deploy this new version and changes to NPM?

**Comment by nihgwu** [comment]
@milindagrawal will release with #32

**Pull request merged**
